### PR TITLE
Add preventThrowingErrors option

### PR DESCRIPTION
**Pull request by tarmolov**
//cc @dfilatov @lemmy- @twoRoger

### CODE REVIEW

**Comment by lemmy-** [comment]
Ok

**Comment by dfilatov** [comment]
:shipit:

**Comment by twoRoger** [comment]
@tarmolov Are you going to add an option for every questionable implementation detail? It seems like a way to total mess. Don't be so compliant)

**Comment by tarmolov** [comment]
@twoRoger Of course, I don't. 

@dfilatov arguments persuaded me to add an option but I didn't like the idea to change the default behavior.

If we have a total mess with options, we'll publish `2.0` with a clean options list and different default behavior ;)

**Comment by tarmolov** [comment]
1.4.0

**Pull request merged**
